import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/main-header";


//metadata is reserved name
//Its like <head>. All the content that goes in head goes in Metadata
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

//This component renders HTML element and Content of the Page
//General HTML skeleton
//Layout is the Wrapper
//Page is the content i.e {chidren}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200 font-mono">
        {/* Header is Standard React Component */}
        <Header />
        {/* children is the content from page.tsx - Home() */}
        {children}
      </body>
    </html>
  );
}
